### ISSUE TITLE
Add an option for archiving generated patches and configs

### ISSUE THREAD

**Issue by chicxurug** [FrontEndART/AIFix4SecCode#43]
Add a new parameter in the config.properties file, called "archive_enabled", which is a boolean value. If this parameter is set to true, all the patches and description.xml files generated during the framework run should be kept as a zipped archive file in the folder "archive" within the result path. If it is false, we don't keep these files, rather delete them (the default behaviour now).

**Comment by searchlab-team** [comment]
Should all the patch files be archived even the ones that are not deleted in the default behavior after the software finished running?
![image](https://user-images.githubusercontent.com/94921513/155998519-25f9648c-b8e0-454f-be3c-9745f0ab1750.png)

Now the patches and the osa_xml directories contain all the patch and the description.xml files. Should the directories be kept if the "archive_enabled" value is true?
![image](https://user-images.githubusercontent.com/94921513/155996559-8b4e0ebf-2304-4ae3-b33d-43762f640e61.png)

**Comment by chicxurug** [comment]
Yes, the directories should be kept as well as the final patches. The best option I think would be to use an archive directory that can be set up in the config file as well. Under this archive directory a timestamp directory should appear with the starting time of the code repair flow and all the generated files should be copied there. Finally, this timestamp dir can be zipped to save space.
