### ISSUE TITLE
Enhance console output

### ISSUE THREAD

**Issue by chicxurug** [FrontEndART/AIFix4SecCode#45]
Right now, the console contains all the outputs of all the intermediate tools we run. Consolidate that by redirecting all the current info into the log file and keep only monitoring messages in the console, something like:
```
[TIMESTAMP] Project source acquired
[TIMESTAMP] Code analysis started
[TIMESTAMP] Detected 12 vulnerabilities
[TIMESTAMP] Generating patches for 1/12 vulnerability
[TIMESTAMP] Compiling patches for 1/12 vulnerability
[TIMESTAMP] Verifying patches for 1/12 vulnerability
[TIMESTAMP] Writing out patch candidates for 1/12 vulnerability
...
[TIMESTAMP] Generating patches for 2/12 vulnerability
[TIMESTAMP] Compiling patches for 2/12 vulnerability
[TIMESTAMP] Verifying patches for 2/12 vulnerability
[TIMESTAMP] Writing out patch candidates for 2/12 vulnerability
```

**Comment by fea-devteam** [comment]
It looks like the configuration is hardcoded in the coderepair-1.0.jar as logback.xml. If we modify this configuration, the changes appear.

**Comment by fea-devteam** [comment]
Renaming the `log4j2.xml` included in the project to `logback.xml` will load the configuration file found in the resources directory properly (this is a logback configuration format, not log4j2).

**Comment by chicxurug** [comment]
The console output is very well consolidated now. Two minor changes needed:
Generating/compiling/verifying patches for 6/8 vulnerability ->Generating/compiling/verifying patches for vulnerability 6/8 
Writing out patch candidates patches for 7/8 vulnerability -> Writing out candidate patches for vulnerability 7/8
