### ISSUE TITLE
Fix generated vscode-config.json

### ISSUE THREAD

**Issue by chicxurug** [FrontEndART/AIFix4SecCode#48]
Currently, if we have multiple instances of the same warning type, it will be generated with a counter postfix into the vscode-config.json file. Instead, the config should group all the warning instances within the same warning type.

**Comment by searchlab-team** [comment]
I'm not sure what the issue is. This picture is from the vscode-config.json file generated from the test-project. For example, do you mean like there is 2 EI_EXPOSE_REP2 warning and these should be under 1 EI_EXPOSE_REP2 warning type?

**Comment by chicxurug** [comment]
Yes, the currently generated json is not right yet, because it wouldnt work if I add something like:

"EI_EXPOSE_REP2": {[
{"patches": [...],
 "textRange": {...}},
{"patches": [...],
 "textRange": {...}},
{"patches": [...],
 "textRange": {...}}
]}

This is the format I would like to use and on the plug-in to show one EI_EXPOSE_REP2 group item that you can expand and list all three actual instances.

**Comment by chicxurug** [comment]
I will add a sample json config I would like to be working.

**Comment by chicxurug** [comment]
The vscode-config.json is the configuration that is working now, we instead would like the form in vscode-config-grouped.

However, for this to work, #59 should be implemented on the plug-in side, so let's freeze this issue until then.

[vscode-config.json.txt](https://github.com/FrontEndART/AIFix4SecCode/files/8231206/vscode-config.json.txt)
[vscode-config-grouped.json.txt](https://github.com/FrontEndART/AIFix4SecCode/files/8231207/vscode-config-grouped.json.txt)

**Comment by chicxurug** [comment]
Coomit [86c6caf](https://github.com/FrontEndART/AIFix4SecCode/commit/86c6caf0de5ec6cfdf06db1535ec2e126ea7a244) fixes the issue. VSCode pulgin is working again.
