### ISSUE TITLE
Test the framework on real-world systems

### ISSUE THREAD

**Issue by chicxurug** [FrontEndART/AIFix4SecCode#70]
Program;EI_EXPOSE_REP2;EI_EXPOSE_REP;NP_NULL_ON_SOME_PATH;MS_SHOULD_BE_FINAL;MS_MUTABLE_
antlr4-4;0;2;6;4;19
arduino;2;0;17;2;9
dolphin_scheduler;143;116;6;3;2
mapdb;3;6;5;3;0
titan_core;5;7;33;4;8
guava;0;0;87;0;0
easyexcel;2;2;0;13;2

**Comment by fea-devteam** [comment]
- [ ] **antlr4-4**
- [ ] **arduino**
- [ ] **dolphin_scheduler**
- [ ] **mapdb** : Detected 4 vulnerabilities
- 4x EI_EXPOSE_REP2
- [ ] **titan/titan-core** : Detected 20 vulnerabilities
- 10x EI_EXPOSE_REP2
- 5x MS_SHOULD_BE_FINAL
- 5x NP_NULL_ON_SOME_PATH
- [ ] **guava/guava** : Detected 23 vulnerabilities
- 23x : NP_NULL_ON_SOME_PATH
- [ ] **easyexcel/easyexcel-core** : Detected 15 vulnerabilities
-  12x : MS_SHOULD_BE_FINAL
-  3x   : EI_EXPOSE_REP2
